# Makefile for GNU Make.
# $Id: GNUmakefile 1 2004-10-11 20:14:37Z hex $

include ../Makedefs.faerion.include

TARGET = library.static
PROG   = parautil.a
SRCS   = $(wildcard *.cc)
DEFS  += MDF_SOEXT=\"$(MDF_SOEXT)\"

include ../Makedefs.faerion
