import os
Import('env', 'fae')

envmod = env.Copy()
envmod.Append(
	category = 'mod',
	LIBPATH = '#/core',
	LIBS = 'parabellym',
	CPPDEFINES = [('funs', 'funsmod')])

for mod in ['autotest', 'test-send', 'test-wait']:
	envmod.SharedLibrary(mod, fae.compile(envmod, [mod, '../util']))

# vim:ts=2:sts=2:sw=2:noet:syntax=python
