import os
Import('env', 'fnd')

envcore = env.Copy()
envcore.Append(CPPDEFINES = ['PARA_BUILD_CORE', ('funs', 'funspcore')])
objs = []

for item in fnd.listFiles(['.', '../util'], r'^.*(\.cc)$'):
	fname, ext = os.path.splitext(item)
	objs.append(envcore.SharedObject(fname + '.core.o', item))

envcore.SharedLibrary('parabellym', objs)

# vim:ts=2:sts=2:sw=2:syntax=python
